name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Debug Environment
      run: |
        python --version
        pip list

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python q1q2.py

    - name: Upload plots as artifacts
      uses: actions/upload-artifact@v2.8.0
      with:
        name: plots
        path: '*.png'
